site_name: Brane Docs
theme:
  name: material  # mkdocs, readthedocs,material

docs_dir: docs

nav:
  - Overview: index.md

  - Brane Specification:
      - Overview: brane-spec/index.md
      - "1. Introduction": brane-spec/01-introduction.md
      - "2. Architectural Overview": brane-spec/02-architecture.md
      - "3. Component Specifications": brane-spec/03-components.md
      - "4. Data and Configuration Model": brane-spec/04-data-config.md
      - "5. Workflow Internal Representation (WIR)": brane-spec/05-wir.md
      - "6. Virtual Machine (VM) Design": brane-spec/06-vm.md
      - "7. BraneScript Frontend": brane-spec/07-branescript.md
      - "8. Extensibility and Future Work": brane-spec/08-extensibility.md
      - "9. References and Related Work": brane-spec/09-references.md

  - Brane User Guide:
      - Overview: brane-user-guide/index.md
      - "1. Introduction": brane-user-guide/01-introduction.md
      - "2. Quick Start for Scientists": brane-user-guide/02-quick-start-scientists.md
      - "3. System Engineers: Deploying Brane": brane-user-guide/03-system-engineers-deploying.md
      - "4. Software Engineers": brane-user-guide/04-software-engineers.md
      - "5. Data Policy Experts": brane-user-guide/05-data-policy-experts.md
      - "6. Scientists: Workflows & Datasets": brane-user-guide/06-Scientists.md
      - "7. Administrators": brane-user-guide/07-Administrators.md

  - Brane Tutorials:
      - Overview: brane-tutorials/index.md
      - "1. Tutorial Overview": brane-tutorials/01-overview.md
      - "2. Introduction": brane-tutorials/02-introduction.md
      - "3. Hello World Example": brane-tutorials/02-hello-world-example.md
      - "4. Hello World Part 2": brane-tutorials/03-hello-world-part2.md
      - "5. Disaster Tweets Example": brane-tutorials/03-disaster-tweets-example.md
      - "6. Scenario: ICT.OPEN 2023": brane-tutorials/04-scenario-ictopen.md
      - "7. Scenario: UMC Utrecht Demo & Workshop": brane-tutorials/05-scenario-umc-utrecht.md

  - FAQ: faq.md
#  - Legacy (optional):
#      - Installation (old): legacy/installation.md
#      - Getting Started (old): legacy/getting-started.md
#      - Developer Guide (old): legacy/developer-guide.md
#      - Admin Guide (old): legacy/admin-guide.md
#      - BraneScript Guide (old): legacy/branescript-guide.md
#      - Tutorials (old): legacy/tutorials.md
