site_name: Brane Docs
theme:
  name: mkdocs  # mkdocs, readthedocs, 

docs_dir: docs

nav:
  - Overview: index.md

  - Brane Specification:
      - Overview: brane-spec/index.md
      - "1. Introduction": brane-spec/01-introduction.md
      - "2. Architectural Overview": brane-spec/02-architecture.md
      - "3. Component Specifications": brane-spec/03-components.md
      - "4. Data and Configuration Model": brane-spec/04-data-config.md
      - "5. Workflow Internal Representation (WIR)": brane-spec/05-wir.md
      - "6. Virtual Machine (VM) Design": brane-spec/06-vm.md
      - "7. BraneScript Frontend": brane-spec/07-branescript.md
      - "8. Extensibility and Future Work": brane-spec/08-extensibility.md
      - "9. References and Related Work": brane-spec/09-references.md

  - Brane User Guide:
      - Overview: brane-user-guide/index.md
      - "1. Introduction": brane-user-guide/01-introduction.md
      - "2. Quick Start for Scientists": brane-user-guide/02-quick-start-scientists.md
      - "3. System Engineers: Deploying Brane": brane-user-guide/03-system-engineers-deploying.md
      - "4. Software Engineers: Developing Packages": brane-user-guide/04-software-developers-packages.md
      - "5. Data Policy Experts / Data Stewards": brane-user-guide/05-policy-experts.md
      - "6. Scientists: Workflows & Datasets": brane-user-guide/06-scientists-workflows.md
      - "7. Administrators: Instances & Credentials": brane-user-guide/07-admins-instances.md
      - "8. Reference": brane-user-guide/08-reference.md

  - Brane Tutorials:
      - Overview: brane-tutorials/index.md
      - "1. Tutorial Overview": brane-tutorials/01-overview.md
      - "2. Hello World Package Tutorial": brane-tutorials/02-hello-world-package.md
      - "3. Disaster Tweets Workflow Tutorial": brane-tutorials/03-disaster-tweets-workflow.md
      - "4. Scenario: ICT.OPEN 2023": brane-tutorials/04-scenarios-ictopen.md
      - "5. Scenario: UMC Utrecht Demo & Workshop": brane-tutorials/05-scenarios-umc-utrecht.md

  - Legacy (optional):
      - Installation (old): legacy/installation.md
      - Getting Started (old): legacy/getting-started.md
      - Developer Guide (old): legacy/developer-guide.md
      - Admin Guide (old): legacy/admin-guide.md
      - BraneScript Guide (old): legacy/branescript-guide.md
      - Tutorials (old): legacy/tutorials.md
